joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.181661565
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.181661565
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.443460953
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_4:
    has_velocity_limits: true
    max_velocity: 3.490658504
    has_acceleration_limits: true
    max_acceleration: 1.5
  joint_5:
    has_velocity_limits: true
    max_velocity: 3.490658504
    has_acceleration_limits: true
    max_acceleration: 1.5
  joint_6:
    has_velocity_limits: true
    max_velocity: 3.490658504
    has_acceleration_limits: true
    max_acceleration: 1.5
